### ISSUE TITLE
Sample not working

### ISSUE THREAD

**Issue by texeratx** [GoogleChrome/custom-tabs-client#10]
When I use chrome beta and click on "Connect to the service":

08-06 15:15:17.924  22257-22257/org.chromium.customtabsclient.example E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.chromium.customtabsclient.example, PID: 22257
    java.lang.SecurityException: Not allowed to bind to service Intent { act=android.support.customtabs.action.CustomTabsService pkg=com.chrome.beta }
            at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1801)
            at android.app.ContextImpl.bindService(ContextImpl.java:1765)
            at android.content.ContextWrapper.bindService(ContextWrapper.java:539)
            at android.support.customtabs.CustomTabsClient.bindCustomTabsService(CustomTabsClient.java:60)
            at org.chromium.customtabsclient.MainActivity.bindCustomTabsService(MainActivity.java:95)
            at org.chromium.customtabsclient.MainActivity.onClick(MainActivity.java:125)
            at android.view.View.performClick(View.java:4780)
            at android.view.View$PerformClick.run(View.java:19866)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by andreban** [comment]
There's a bug on Chrome Beta where the Custom Tab service was not exported. It will be fixed in the next release. You can test the code against Chrome Dev meanwhile.
