### ISSUE TITLE
Bug: crash in case Chrome is disabled/removed/old, in case the app used it shortly before

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [GoogleChrome/custom-tabs-client#23]
scenario:
open "demos" sample, and press the first item. close activity to go to the main one.
go to the app-info screen of Chrome app and disable it, and quickly switch to the sample app and choose the first item. 
Then it crashes. 

It shows this exception:

10-15 12:28:57.321 7342-7342/? E/AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=http://developer.android.com pkg=com.android.chrome (has extras) }
10-15 12:28:57.321 7342-7342/? E/AndroidRuntime:     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1781)
10-15 12:28:57.321 7342-7342/? E/AndroidRuntime:     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
10-15 12:28:57.321 7342-7342/? E/AndroidRuntime:     at android.app.Activity.startActivityForResult(Activity.java:3745)
10-15 12:28:57.321 7342-7342/? E/AndroidRuntime:     at android.app.Activity.startActivity(Activity.java:4012)
10-15 12:28:57.321 7342-7342/? E/AndroidRuntime:     at android.support.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:150)
10-15 12:28:57.321 7342-7342/? E/AndroidRuntime:     at org.chromium.customtabsdemos.CustomTabActivityHelper.openCustomTab(CustomTabActivityHelper.java:65)
10-15 12:28:57.321 7342-7342/? E/AndroidRuntime:     at org.chromium.customtabsdemos.CustomUIActivity.openCustomTab(CustomUIActivity.java:129)
10-15 12:28:57.321 7342-7342/? E/AndroidRuntime:     at org.chromium.customtabsdemos.CustomUIActivity.onClick(CustomUIActivity.java:79)
10-15 12:28:57.321 7342-7342/? E/AndroidRuntime:     at android.view.View.performClick(View.java:4780)
10-15 12:28:57.321 7342-7342/? E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:19866)
10-15 12:28:57.321 7342-7342/? E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
10-15 12:28:57.321 7342-7342/? E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-15 12:28:57.321 7342-7342/? E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
10-15 12:28:57.321 7342-7342/? E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254)
10-15 12:28:57.321 7342-7342/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
10-15 12:28:57.321 7342-7342/? E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
10-15 12:28:57.321 7342-7342/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
10-15 12:28:57.321 7342-7342/? E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

In case I choose to revert Chrome to an older version and try the app, it will cause Chrome itself to crash.

**Comment by AndroidDeveloperLB** [comment]
I also think the sample doesn't check for the version of Chrome, so if you only revert to old versions of chrome, it's chrome itself that crashes.

**Comment by AndroidDeveloperLB** [comment]
I think I know the reason for this:
you cache the package-name of the chorme app to use, but you don't check if it will work before you use it again.
The solution is to either use a safer cache mechanism, or not use a cache mechanism at all.

**Comment by AndroidDeveloperLB** [comment]
Here's my suggestion of how to fix it, in case you use the easy solution of not using a cached package name:

CustomTabsHelper.java

    public static String getPackageNameToUse(Context context) {
        PackageManager pm = context.getPackageManager();
        // Get default VIEW intent handler.
        Intent activityIntent = new Intent(Intent.ACTION_VIEW, Uri.parse("http://www.example.com"));
        ResolveInfo defaultViewHandlerInfo = pm.resolveActivity(activityIntent, 0);
        String defaultViewHandlerPackageName = null;
        if (defaultViewHandlerInfo != null) {
            defaultViewHandlerPackageName = defaultViewHandlerInfo.activityInfo.packageName;
        }

        // Get all apps that can handle VIEW intents.
        List<ResolveInfo> resolvedActivityList = pm.queryIntentActivities(activityIntent, 0);
        List<String> packagesSupportingCustomTabs = new ArrayList<>();
        for (ResolveInfo info : resolvedActivityList) {
            Intent serviceIntent = new Intent();
            serviceIntent.setAction(ACTION_CUSTOM_TABS_CONNECTION);
            serviceIntent.setPackage(info.activityInfo.packageName);
            if (pm.resolveService(serviceIntent, 0) != null)
                packagesSupportingCustomTabs.add(info.activityInfo.packageName);
        }

        // Now packagesSupportingCustomTabs contains all apps that can handle both VIEW intents
        // and service calls.
        if (packagesSupportingCustomTabs.isEmpty())
            return null;
        if (packagesSupportingCustomTabs.size() == 1) {
            return packagesSupportingCustomTabs.get(0);
        } else if (!TextUtils.isEmpty(defaultViewHandlerPackageName)
                && !hasSpecializedHandlerIntents(context, activityIntent)
                && packagesSupportingCustomTabs.contains(defaultViewHandlerPackageName)) {
            return defaultViewHandlerPackageName;
        }
        String packageNameToUse = null;
        for (String packageName : packagesSupportingCustomTabs) {
            switch (packageName) {
                case STABLE_PACKAGE:
                    return STABLE_PACKAGE;
                case BETA_PACKAGE:
                    packageNameToUse = packageName;
                    break;
                case DEV_PACKAGE:
                    if (packageNameToUse == LOCAL_PACKAGE)
                        packageNameToUse = DEV_PACKAGE;
                    break;
                case LOCAL_PACKAGE:
                    if (packageNameToUse == null)
                        packageNameToUse = LOCAL_PACKAGE;
                    break;
            }
        }
        return packageNameToUse;
    }

**Comment by AndroidDeveloperLB** [comment]
If you wish to have a better caching mechanism, I suggest to have a broadcastReceiver for the changes of apps (uninstall, change, install...), and reset the cached package name for each time there is a change that might change the result.

**Comment by pasko** [comment]
please file a bug using the link suggested at the end of the README.md

**Comment by AndroidDeveloperLB** [comment]
@pasko But it's a bug on this repo. Not in the library. It's inside the file "CustomTabsHelper" which is a part of the repo. 
It is caused because you cache the package name to handle, and didn't think about the end case of what happens to it after you cache it.

**Comment by pasko** [comment]
I'll file it for you now.

Issues for this repo should also be there. The reason is: we already have a process for those bugs ensuring they will be looked at, including by maintainers of the code in this repo. We don't want to create too many processes :)

**Comment by pasko** [comment]
done: https://code.google.com/p/chromium/issues/detail?id=543553

please continue there

**Comment by AndroidDeveloperLB** [comment]
What do you mean you have a process? You have a PC that has a process for monitoring what's going on there, and you don't want to have one here too?
Or a process in a more abstract manner?
