### ISSUE TITLE
IllegalArgumentException when calling startActivity

### ISSUE THREAD

**Issue by magnusgronbek** [GoogleChrome/custom-tabs-client#5]
Steps to reproduce exception:
* Press button Launch URL in Chrome tab
* Go back when custom tab is launched
* Exit app with backkey
* Start app again
* Press button Launch URL in Chrome tab

Then I get the following exception:

06-15 19:43:53.457  32194-32194/org.chromium.customtabsclient.example D/AndroidRuntime﹕ Shutting down VM
06-15 19:43:53.458  32194-32194/org.chromium.customtabsclient.example E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.chromium.customtabsclient.example, PID: 32194
    java.lang.IllegalArgumentException
            at android.os.Parcel.readException(Parcel.java:1550)
            at android.os.Parcel.readException(Parcel.java:1499)
            at android.app.ActivityManagerProxy.isTopOfTask(ActivityManagerNative.java:4524)
            at android.app.Activity.isTopOfTask(Activity.java:5407)
            at android.app.Activity.startActivityForResult(Activity.java:3779)
            at android.app.Activity.startActivity(Activity.java:4012)
            at org.chromium.customtabsclient.CustomTabActivityManager.sendIntent(CustomTabActivityManager.java:344)
            at org.chromium.customtabsclient.CustomTabActivityManager.access$900(CustomTabActivityManager.java:49)
            at org.chromium.customtabsclient.CustomTabActivityManager$3.run(CustomTabActivityManager.java:325)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
06-15 19:43:54.338  32194-32211/org.chromium.customtabsclient.example W/CustomTabsClientExample﹕ onUserNavigationStarted: url = http://www.android.com/

**Comment by pasko** [comment]
cannot reproduce with the latest example, can you try it again with stuff I pushed today?
