### ISSUE TITLE
Sample not working

### ISSUE THREAD

**Issue by texeratx** [GoogleChrome/custom-tabs-client#9]
When i use chrome dev and click on "Launch URL in a Chrome Custon Tab":

08-06 15:13:06.208  19674-19674/org.chromium.customtabsclient.example E/ActivityThread﹕ Activity org.chromium.customtabsclient.MainActivity has leaked ServiceConnection org.chromium.customtabsclient.MainActivity$2@ec55483 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity org.chromium.customtabsclient.MainActivity has leaked ServiceConnection org.chromium.customtabsclient.MainActivity$2@ec55483 that was originally bound here
            at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1077)
            at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:971)
            at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1782)
            at android.app.ContextImpl.bindService(ContextImpl.java:1765)
            at android.content.ContextWrapper.bindService(ContextWrapper.java:539)
            at android.support.customtabs.CustomTabsClient.bindCustomTabsService(CustomTabsClient.java:60)
            at org.chromium.customtabsclient.MainActivity.bindCustomTabsService(MainActivity.java:95)
            at org.chromium.customtabsclient.MainActivity.onClick(MainActivity.java:125)
            at android.view.View.performClick(View.java:4780)
            at android.view.View$PerformClick.run(View.java:19866)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by pasko** [comment]
If you are still seeing this, please use the link at the bottom of README.md to report bugs. This way the bugs get addressed faster.

Please also provide details into your environment (versions, basically).
